language: scala
before_script: ./make_credentials.sh
script: sbt test

env:
  global:
    - secure: "ls8xKxauQ8Jb6PGRPPdjrIeIGK5gTlL9R3wgAtD1oHtJ7MJgFzSndM6reFI47rjnRoxYvw7kGQ2QjJ+PEc7q9BF3ut1QPPIeq2cqNp7l7qS9yxzpQt26SQNnE91nZxCZ2sxnule72ggY7hkCdgH6pxQnsmHRQqXFeZzL7Q6L0Fs="
    - secure: "S6frXN1glDWVLGacehrhiFo5AWY8rRcyhPpCNBPlYbaOOEEZZlBV1Zht6fTQiKvWAccXxbYMbvsU9KznKzhITq4PS/4fhfOfpahjaF5x/Ag9OTi09RnGNH+TDLQ+xEcyfpqeWTsSI4aTU03ijihB3TnvXMKzSpiZzmjPFSvxEQI="

# Publish to Sonatype if building master
after_success:
  - "[[ $TRAVIS_BRANCH == \"master\" ]] && [[ $TRAVIS_PULL_REQUEST == \"false\" ]] && sbt publish"